spring:
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:h2:mem:ecommerce;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "change-this-dev-secret-key-min-32-chars!!"
  expiration-ms: 86400000

app:
  cors:
    allowed-origins: "http://localhost:4200"
